"""Golden-file tests: a known WAV must always produce the same bytes.

Every other test in this suite asserts a property -- that framing is 160 bytes,
that SNR clears a threshold, that base64 decodes once. Properties can all hold
while the output still changes. This file pins the actual bytes, so any change
to the codec tables, the resampler, the framing or the base64 layering shows up
as a diff rather than as a subtly different stream that still passes.

The golden file is committed. To regenerate it after an *intentional* change::

    UPDATE_GOLDEN=1 python -m pytest tests/test_golden.py

Regenerating should be a deliberate act with a reason in the commit message. If
the golden hashes change and you did not mean them to, that is the test working.
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
from pathlib import Path

import pytest

from streamdouble import audio
from streamdouble.protocol import MediaStreamEncoder, StreamIdentity

GOLDEN_PATH = Path(__file__).parent / "golden" / "frames.json"

UPDATE_GOLDEN = os.environ.get("UPDATE_GOLDEN") == "1"

#: Fixed SIDs so that golden JSON frames are reproducible. Real sessions
#: randomise these; the golden test is the one place that must not.
GOLDEN_IDENTITY = StreamIdentity(
    stream_sid="MZ00000000000000000000000000000001",
    account_sid="AC00000000000000000000000000000002",
    call_sid="CA00000000000000000000000000000003",
)

#: Fixtures to pin, chosen to cover the distinct paths into the encoder:
#: native-rate mono, a file needing resampling and downmixing, one needing
#: padding, and full-scale content that exercises the codec's top segment.
GOLDEN_FIXTURES = [
    "speech_8k.wav",
    "silence_8k.wav",
    "tone_440_8k.wav",
    "partial_frame_8k.wav",
    "speech_16k.wav",
    "speech_44k_stereo.wav",
]


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def describe_fixture(path: Path) -> dict:
    """Compute the golden record for one fixture.

    Records a hash of the whole mu-law stream, plus the first and last frames
    verbatim. The hash is what actually pins the bytes; the verbatim frames are
    there so that a failure is debuggable by eye rather than being a bare
    "hash differs".
    """
    frames = audio.wav_to_ulaw_frames(path)
    joined = b"".join(frames)
    return {
        "frame_count": len(frames),
        "total_bytes": len(joined),
        "ulaw_sha256": sha256_hex(joined),
        "first_frame_hex": frames[0].hex(),
        "last_frame_hex": frames[-1].hex(),
    }


def describe_json_frames(path: Path, limit: int = 3) -> dict:
    """Golden record for the fully-assembled JSON frames.

    Pins the protocol layer on top of the audio layer: field names, JSON types,
    counter values and the base64 encoding, all in the exact form that goes on
    the wire.
    """
    encoder = MediaStreamEncoder(GOLDEN_IDENTITY)
    messages = [json.dumps(encoder.connected()), json.dumps(encoder.start())]
    for media_frame in audio.wav_to_ulaw_frames(path)[:limit]:
        messages.append(json.dumps(encoder.media(media_frame)))
    messages.append(json.dumps(encoder.stop()))
    return {
        "messages": messages,
        "sha256": sha256_hex("\n".join(messages).encode()),
    }


def build_golden(fixture_dir: Path) -> dict:
    return {
        "_comment": (
            "Generated by tests/test_golden.py. Regenerate with "
            "UPDATE_GOLDEN=1 python -m pytest tests/test_golden.py"
        ),
        "audio": {name: describe_fixture(fixture_dir / name) for name in GOLDEN_FIXTURES},
        "protocol": describe_json_frames(fixture_dir / "speech_8k.wav"),
    }


@pytest.fixture(scope="module")
def golden(fixture_dir: Path) -> dict:
    """Load the committed golden file, regenerating it when asked to."""
    if UPDATE_GOLDEN:
        GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
        GOLDEN_PATH.write_text(json.dumps(build_golden(fixture_dir), indent=2) + "\n")

    if not GOLDEN_PATH.exists():
        pytest.fail(
            f"golden file {GOLDEN_PATH} is missing; create it with "
            "UPDATE_GOLDEN=1 python -m pytest tests/test_golden.py"
        )
    return json.loads(GOLDEN_PATH.read_text())


@pytest.mark.parametrize("name", GOLDEN_FIXTURES)
def test_audio_bytes_are_unchanged(golden, fixture_dir, name):
    """The mu-law byte stream for each fixture matches the golden record."""
    expected = golden["audio"][name]
    actual = describe_fixture(fixture_dir / name)

    # Compare the cheap, readable fields first so a failure names the difference
    # rather than only reporting that two hashes disagree.
    assert actual["frame_count"] == expected["frame_count"]
    assert actual["total_bytes"] == expected["total_bytes"]
    assert actual["first_frame_hex"] == expected["first_frame_hex"]
    assert actual["last_frame_hex"] == expected["last_frame_hex"]
    assert actual["ulaw_sha256"] == expected["ulaw_sha256"]


def test_protocol_frames_are_unchanged(golden, fixture_dir):
    """The assembled JSON frames match byte-for-byte."""
    expected = golden["protocol"]
    actual = describe_json_frames(fixture_dir / "speech_8k.wav")

    assert actual["messages"] == expected["messages"]
    assert actual["sha256"] == expected["sha256"]


def test_golden_frames_are_all_the_right_size(golden):
    """Every pinned frame is exactly 160 bytes.

    A standing check on the golden data itself: if a future regeneration ever
    records a differently-sized frame, that is caught here rather than being
    quietly blessed as the new expected output.
    """
    for name, record in golden["audio"].items():
        assert len(record["first_frame_hex"]) == audio.FRAME_BYTES * 2, name
        assert len(record["last_frame_hex"]) == audio.FRAME_BYTES * 2, name
        assert record["total_bytes"] == record["frame_count"] * audio.FRAME_BYTES, name


def test_golden_silence_is_actually_silent(golden):
    """The silence fixture pins to 0xFF bytes.

    A cheap tripwire on the codec's sign convention: if silence ever encodes to
    0x00, this fails immediately and unambiguously.
    """
    record = golden["audio"]["silence_8k.wav"]
    assert set(bytes.fromhex(record["first_frame_hex"])) == {0xFF}
    assert set(bytes.fromhex(record["last_frame_hex"])) == {0xFF}


def test_golden_protocol_payloads_decode_to_single_frames(golden):
    """Each pinned media payload base64-decodes once to exactly 160 bytes."""
    for message in golden["protocol"]["messages"]:
        parsed = json.loads(message)
        if parsed["event"] != "media":
            continue
        decoded = base64.b64decode(parsed["media"]["payload"], validate=True)
        assert len(decoded) == audio.FRAME_BYTES
